import { ListMessagesComponent } from "@/components/ListMessages";
import { SendMessagesComponent } from "@/components/SendMessages";
import UserProvider, { UserContext } from "@/contexts/User";
import useSocket from "@/hooks/useSocket";
import { MessageInterface } from "@/interface/message";
import Head from "next/head";
import { useContext, useRef, useState } from "react";
import styled from "styled-components";

export default function Home() {
  const listRef = useRef<HTMLDivElement>(null);
  const { messages, setMessages } = useSocket();
  return (
    <>
      <Head>
        <title>Messageria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <PageContent>
          <ListMessagesComponent
            listRef={listRef}
            messageList={messages}
            setMessageList={setMessages}
          />
          <SendMessagesComponent
            listRef={listRef}
            setMessageList={setMessages}
          />
        </PageContent>
      </PageContainer>
    </>
  );
}

const PageContainer = styled.div`
  width: 100vw;
  height: 100vh;
  background: ${({ theme }) => theme.green900};
  display: flex;
  align-items: center;
  justify-content: center;

  @media (max-width: 1200px) {
    padding: 24px 24px 0 24px;
    width: calc(100vw - 48px);
    max-height: calc(100vh - 24px);
  }
`;

const PageContent = styled.div`
  width: 1344px;
  height: 926px;
  display: flex;
  flex-direction: column;
  gap: 24px;

  @media (max-width: 1200px) {
    width: 100%;
    height: 100%;
  }
`;
